name: "🚀 release"

on:
    push:
        branches:
          - main

jobs:
    release:
        name: 🚀 release
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2.4.2
            - name: 🟢 node
              uses: setup-node@v3.4.1
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
            - name: 🚀 publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
